---
title: "1.DataPreprocessing"
output: html_document
date: "2023-03-02"
---
#Libraries
```{r}
# load the lubridate library for date-time operations
library(lubridate)
library(dplyr)
library(ggplot2)
#install.packages("weights")
#install.packages("vars")
library(forecast)
library(vars)
library(tidyverse)
library(xts)
library(tibbletime)
library(tidyquant)
library(SnowballC)
library(quantmod)
library(syuzhet)
library(gridExtra)
#library(weights)
library(GGally)

library(caret)


```

#Load Data and preprocessing 
```{r}
#load tweet data and stock data
load("allDataNoTweet_vf1b1Mar19_protect.RData")
load("stock_feb1Mar19.RData")

#keep tweet data only of the weekdays when the stock market is open
# filter the data frame to keep only weekdays
sentimentData <- allDataNoTweet[wday(allDataNoTweet$roundTimeEnd, label = TRUE) %in% c("Mon", "Tue", "Wed", "Thu", "Fri"),]

#convert stcok date to NY date
stock$Datetime <- ymd_hms(stock$Datetime, tz = "America/New_York")
colnames(stock[3])<-"company"

#add company name 
stock <- stock %>%
  mutate(company_name = case_when(
    comapany == "abbv" ~ "AbbVie",
    comapany == "mrk" ~ "Merck",
    comapany == "pfe" ~ "Pfizer",
    comapany == "azn" ~ "AstraZeneca",
    comapany == "mrna" ~ "Moderna",
    comapany == "rhhby" ~ "Roche",
    comapany == "lly" ~ "EliLilly",
    comapany == "nvo" ~ "Nordisk",
    comapany == "jnj" ~ "JohnsonJohnson",
    comapany == "nvs" ~ "Novartis",
    TRUE ~ NA_character_
  ))

```

#Indivudal data frames of sentiments
```{r}

#Select companies
companyData <- sentimentData %>% filter(!is.na(company))
# Join the stock data to the company data
companyData <- left_join(companyData, stock[c("Datetime", "Open", "company_name")], 
                          by = c("roundTimeEnd" = "Datetime", "company" = "company_name"))
# Convert date/time columns to appropriate formats
#companyData$created_at <- as.POSIXct(companyData$created_at, format = "%Y-%m-%d %H:%M:%S")
companyData$roundTimeEnd <- as.POSIXct(companyData$roundTimeEnd)
# Filter to only include data for weekdays, from 9:30am to 15:30pm, and from Feb 1 to Feb 19
companyData <- companyData %>% 
  filter(weekdays(roundTimeEnd) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),
         hour(roundTimeEnd) >= 9, hour(roundTimeEnd) <= 16, 
         roundTimeEnd >= as.POSIXct("2023-02-01"), roundTimeEnd <= as.POSIXct("2023-03-19"))
#calculate average
companyData$overall<-as.numeric(companyData$overall)
OverallcompanyData<-companyData %>%
  group_by(company, roundTimeEnd, Open) %>%
  summarise(overallAvg = mean(overall)) 
#weighted mean 
#companyDataOverallW <- companyData %>%
 # dplyr::group_by(roundTimeEnd, Open, company) %>%
  #dplyr::summarise(n = n(), overall_mean = mean(overall, na.rm = TRUE)) %>%
  #dplyr::ungroup() %>%
  #weights::weight_mean(w = n, x = overall_mean)
colnames(OverallcompanyData)[4]<-"companyS"
colnames(OverallcompanyData)[1]<-"company"
OverallcompanyData <- OverallcompanyData %>%
                        filter(!as.Date(roundTimeEnd) == as.Date("2023-02-20"))


# CEO data frame 
ceosData <- sentimentData %>% filter(!is.na(ceos))
# Join the stock data to the company data
ceosData <- left_join(ceosData, stock[c("Datetime", "Open", "company_name")], 
                          by = c("roundTimeEnd" = "Datetime", "ceos" = "company_name"))
# Convert date/time columns to appropriate formats
#companyData$created_at <- as.POSIXct(companyData$created_at, format = "%Y-%m-%d %H:%M:%S")
ceosData$roundTimeEnd <- as.POSIXct(ceosData$roundTimeEnd)
# Filter to only include data for weekdays, from 9:30am to 15:30pm, and from Feb 1 to Feb 19
ceosData <- ceosData %>% 
  filter(weekdays(roundTimeEnd) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),
         hour(roundTimeEnd) >= 9, hour(roundTimeEnd) <= 16, 
         roundTimeEnd >= as.POSIXct("2023-02-01"), roundTimeEnd <= as.POSIXct("2023-03-19"))
#calculate average
ceosData$overall<-as.numeric(ceosData$overall)
OverallceosData<-ceosData %>%
  group_by(ceos, roundTimeEnd, Open) %>%
  summarise(overallAvg = mean(overall)) 
#weighted mean 
#companyDataOverallW <- companyData %>%
 # dplyr::group_by(roundTimeEnd, Open, company) %>%
  #dplyr::summarise(n = n(), overall_mean = mean(overall, na.rm = TRUE)) %>%
  #dplyr::ungroup() %>%
  #weights::weight_mean(w = n, x = overall_mean)
colnames(OverallceosData)[4]<-"ceosS"
colnames(OverallceosData)[1]<-"company"
OverallceosData <- OverallceosData %>%
                        filter(!as.Date(roundTimeEnd) == as.Date("2023-02-20"))

#NEWS
newsData <- sentimentData %>% filter(!is.na(news))
# Create data frame with news column = "covid"
covidData <- newsData %>%
  filter(news == "covid")
colnames(covidData)[10]<-"covid"
# Create data frame with news column = "vaccine"
vaccineData <- newsData %>%
  filter(news == "vaccine")
colnames(vaccineData)[10]<-"vaccineS"

#covid data frame 
# Join the stock data to the covid data
covidData <- left_join(covidData, stock[c("Datetime", "Open", "company_name")], 
                          by = c("roundTimeEnd" = "Datetime"))
# Convert date/time columns to appropriate formats
#covidData$created_at <- as.POSIXct(covidData$created_at, format = "%Y-%m-%d %H:%M:%S")
covidData$roundTimeEnd <- as.POSIXct(covidData$roundTimeEnd)
# Filter to only include data for weekdays, from 9:30am to 3:30pm, and from Feb 1 to Feb 19
covidData <- covidData %>% 
  filter(weekdays(roundTimeEnd) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),
         hour(roundTimeEnd) >= 9, hour(created_at) <= 15:30, 
         roundTimeEnd >= as.POSIXct("2023-02-01"), roundTimeEnd <= as.POSIXct("2023-03-19"))
#calculate average
covidData$overall<-as.numeric(covidData$overall)
OverallcovidData<-covidData %>%
  group_by(company_name, roundTimeEnd, Open) %>%
  summarise(overallAvg = mean(overall)) 
#weighted mean 
#covidDataOverallW <- covidData %>%
 # group_by(covid, roundTimeEnd) %>%
  #summarise(n = n(), overall_mean = mean(overall, na.rm = TRUE)) %>%
  #ungroup() %>%
  #weight_mean(w = n, x = overall_mean)
colnames(OverallcovidData)[4]<-"covidS"
colnames(OverallcovidData)[1]<-"company"
OverallcovidData <- OverallcovidData %>%
                        filter(!as.Date(roundTimeEnd) == as.Date("2023-02-20"))

#vaccine data frame 
# Join the stock data to the vaccine data
vaccineData <- left_join(vaccineData, stock[c("Datetime", "Open", "company_name")], 
                          by = c("roundTimeEnd" = "Datetime"))
# Convert date/time columns to appropriate formats
#vaccineData$created_at <- as.POSIXct(vaccineData$created_at, format = "%Y-%m-%d %H:%M:%S")
vaccineData$roundTimeEnd <- as.POSIXct(vaccineData$roundTimeEnd)
# Filter to only include data for weekdays, from 9:30am to 3:30pm, and from Feb 1 to Feb 19
vaccineData <- vaccineData %>% 
  filter(weekdays(roundTimeEnd) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),
         hour(roundTimeEnd) >= 9, hour(roundTimeEnd) <= 15:30, 
         roundTimeEnd >= as.POSIXct("2023-02-01"), roundTimeEnd <= as.POSIXct("2023-03-19"))
#calculate average
vaccineData$overall<-as.numeric(vaccineData$overall)
OverallvaccineData<-vaccineData %>%
  group_by(company_name, roundTimeEnd, Open) %>%
  summarise(overallAvg = mean(overall)) 
#weighted mean 
weight_mean <- function(.data, w, x) {
  sum(w * x, na.rm = TRUE) / sum(w, na.rm = TRUE)
}
#vaccineDataOverallW <- vaccineData %>%
 # group_by(vaccine, roundTimeEnd) %>%
#  summarise(n = n(), overall_mean = mean(overall, na.rm = TRUE)) %>%
 # ungroup() %>%
  #weight_mean(., w = n, x = overall_mean)
colnames(OverallvaccineData)[4]<-"vaccineS"
colnames(OverallvaccineData)[1]<-"company"
OverallcovidData <- OverallcovidData %>%
                        filter(!as.Date(roundTimeEnd) == as.Date("2023-02-20"))

#COMPETITORS
#We are going to sum for one company the overall of the rest of the companies and dived by nice to normalize
OverallcompetitorsData<- OverallcompanyData %>%
  group_by(roundTimeEnd) %>%
  mutate(sum_other_companies = (sum(companyS) - companyS)/9)
OverallcompetitorsData<-OverallcompetitorsData[,-4]
colnames(OverallcompetitorsData)[4]<-"competitorsS"
colnames(OverallcompetitorsData)[1]<-"company"
OverallcompetitorsData <- OverallcompetitorsData %>%
                        filter(!as.Date(roundTimeEnd) == as.Date("2023-02-20"))

#JOIN THE 5 DATA FRAMES 
# join the data frames by company and date
# join companyDataOverall and ceoDataOverall
joined_data <- OverallcompanyData %>%
  left_join(OverallcovidData, by = c("company", "roundTimeEnd", "Open"))
#many joins
joined_data2 <- joined_data %>%
  inner_join( OverallvaccineData, by = c("company", "roundTimeEnd", "Open"))
joined_data3 <- joined_data2 %>%
  left_join(OverallceosData, by = c("company", "roundTimeEnd")) 
joined_data3<-joined_data3[,-7]
colnames(joined_data3)[3]<-"Open"
allSentimentsdata <- joined_data3 %>%
  inner_join( OverallcompetitorsData, by = c("company", "roundTimeEnd", "Open"))

#Save all sentyments
save(allSentimentsdata, file = "allSentiments_vf1b1Mar19.RData")

#Plotting
p<-ggpairs(allSentimentsdata[, c("company", "Open", "companyS", "covidS", "vaccineS", "ceosS", "competitorsS")], 
        mapping = aes(color = company),
        lower = list(corSize = 0.05)) +
  scale_color_discrete()
p
correlation_table <- cor(allSentimentsdata[, c("Open", "companyS", "covidS", "vaccineS", "ceosS", "competitorsS")])
as.table(correlation_table)
```

#ARIMA model
# Only using Historival record
```{r}

# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))

# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata%>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  arima_model <- auto.arima(ts_data, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  c_pred <- forecast(c_model, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


#PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
   ggtitle("Historical Market Prediction") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")




# Evaluate them 
Epredictions_HR <- predictions_df
#MAPE 
mapeHR <- Epredictions_HR %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHR[11,] = c(as.character("Mean"), as.list(mean(mapeHR$mape)))


```


# Historival record and adding sentiments as COVARIATE
#company
```{r}

# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))

# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$companyS)
  colnames(covariates) <- "companyS"
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$companyS)
  colnames(covariates) <- "companyS"
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c( c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
          ggtitle("Market prediction based on perception of companies") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")




# Evaluate them 
# Evaluate them 
Epredictions_HRC <- predictions_df
#MAPE 
mapeHRC <- Epredictions_HRC %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRC[11,] = c(as.character("Mean"), as.list(mean(mapeHRC$mape)))



```


#covid
```{r}

# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))


# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$covidS)
  colnames(covariates) <- "covidS"
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$covidS)
  colnames(covariates) <- "covidS"
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
  ggtitle("Market prediction based on perception of covid") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")





# Evaluate them 
# Evaluate them 
Epredictions_HRCo <- predictions_df
#MAPE 
mapeHRCo <- Epredictions_HRCo %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRCo[11,] = c(as.character("Mean"), as.list(mean(mapeHRCo$mape)))


```

#vaccine
```{r}
# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))

# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$vaccineS)
  colnames(covariates) <- "vaccineS"
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$vaccineS)
  colnames(covariates) <- "vaccineS"
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
  ggtitle("Market prediction based on perception of vaccines") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")




#MAPE
# Evaluate them 
Epredictions_HRV <- predictions_df
#MAPE 
mapeHRV <- Epredictions_HRV %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRV[11,] = c(as.character("Mean"), as.list(mean(mapeHRV$mape)))
```

#ceos
```{r}
# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))

# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$ceosS)
  colnames(covariates) <- "ceosS"
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$ceosS)
  colnames(covariates) <- "ceosS"
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
  ggtitle("Market prediction based on perception of CEOs") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")



# Calculate MAPE
# Evaluate them 
Epredictions_HRCe <- predictions_df
#MAPE 
mapeHRCe <- Epredictions_HRCe %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRCe[11,] = c(as.character("Mean"), as.list(mean(mapeHRCe$mape)))
```

#competitors
```{r}
# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))


# Fit an ARIMA model for each company
models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$competitorsS)
  colnames(covariates) <- "competitorsS"
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$competitorsS)
  colnames(covariates) <- "competitorsS"
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
  ggtitle("Market prediction based on perception of competitors") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")


# MAPE
# Evaluate them 
# Evaluate them 
Epredictions_HRCom <- predictions_df
#MAPE 
mapeHRCom <- Epredictions_HRCom %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRCom[11,] = c(as.character("Mean"), as.list(mean(mapeHRCom$mape)))
```

#All sentiments
```{r}
# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))


models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$companyS, c_data$covidS, c_data$vaccineS, c_data$ceosS, c_data$competitorsS)
  colnames(covariates) <- c("companyS", "covidS", "vaccineS", "ceosS", "competitorsS")
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$companyS, c_test_data$covidS, c_test_data$vaccineS, c_test_data$ceosS, c_test_data$competitorsS)
  colnames(covariates) <- c("companyS", "covidS", "vaccineS", "ceosS", "competitorsS")
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type")+
ggtitle("Market prediction based on the perception of companies, ceos, news and competitors") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")



# MAPE
# Evaluate them 
# Evaluate them 
Epredictions_HRA <- predictions_df
#MAPE 
mapeHRA <- Epredictions_HRA %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRA[11,] = c(as.character("Mean"), as.list(mean(mapeHRA$mape)))
```

#comany and vaccine 
```{r}
# Split data into training and testing sets
train_data <- allSentimentsdata %>% filter(roundTimeEnd >= as.POSIXct("2023-02-01") & roundTimeEnd <= as.POSIXct("2023-03-07"))
test_data <- allSentimentsdata %>% filter(roundTimeEnd > as.POSIXct("2023-03-07") & roundTimeEnd <= as.POSIXct("2023-03-19"))


models <- list()
for (c in unique(allSentimentsdata$company)) {
  c_data <- allSentimentsdata %>% filter(company == c)
  ts_data <- ts(c_data$Open, frequency = 1, start = c_data$roundTimeEnd[1])
  covariates <- cbind(c_data$companyS, c_data$vaccineS)
  colnames(covariates) <- c("companyS", "covidS", "ceosS", "competitorsS")
  arima_model <- auto.arima(ts_data, xreg = covariates, seasonal = FALSE, stepwise = FALSE)
  models[[c]] <- arima_model
}

# Make predictions on the test set
predictions <- list()
for (c in unique(test_data$company)) {
  c_model <- models[[c]]
  c_test_data <- test_data %>% filter(company == c)
  ts_test_data <- ts(c_test_data$Open, frequency = 1, start = c_test_data$roundTimeEnd[1])
  c_pred_values <- c()
  covariates <- cbind(c_test_data$companyS, c_test_data$covidS, c_test_data$ceosS, c_test_data$competitorsS)
  colnames(covariates) <- c("companyS", "covidS", "ceosS", "competitorsS")
  c_pred <- forecast(c_model, xreg = covariates, h = length(ts_test_data))
  c_pred_values <- c(c_pred$mean)
  predictions[[c]] <- c_pred_values
}

# Combine predictions into one dataframe
predictions_df <- data.frame(company = character(),
                             date = as.POSIXct(character()),
                             predicted_open = numeric(),
                             actual_open = numeric(),
                             stringsAsFactors = FALSE)
for (c in unique(test_data$company)) {
  c_test_data <- test_data %>% filter(company == c)
  c_pred_values <- predictions[[c]]
  pred_df <- data.frame(company = c,
                        date = c_test_data$roundTimeEnd,
                        predicted_open = c_pred_values,
                        actual_open = c_test_data$Open,
                        stringsAsFactors = FALSE)
  predictions_df <- rbind(predictions_df, pred_df)
}


##PLOT COMPANIES PREDICTION SEPARATED
##PLOT COMPANIES PREDICTION SEPARATED
##PLOT COMPANIES PREDICTION SEPARATED
ggplot(predictions_df, aes(x = date, y = predicted_open, group = company)) +
  geom_blank(data = predictions_df %>% filter(weekdays(date) == "Saturday" | weekdays(date) == "Sunday")) +
  geom_line(aes(color = "Predicted")) +
  geom_line(aes(y = actual_open, color = "Actual")) +
  scale_color_manual(values = c("Predicted" = "red", "Actual" = "blue")) +
  facet_wrap(~ company, scales = "free_y") +
  labs(x = "Date", y = "Open Price", color = "Price Type") +
  ggtitle("Market prediction based on the perception of companies and vaccines") +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %d", date_breaks = "3 day", expand = c(0, 0)) 
ggsave("Fig4_stockPrediction_historicalseparated.png")


# MAPE
# Evaluate them 
# Evaluate them 
Epredictions_HRCV <- predictions_df
#MAPE 
mapeHRCV <- Epredictions_HRCV %>%
  dplyr::group_by(company) %>%
  dplyr::summarize(mape = mean(abs((actual_open - predicted_open)/actual_open)) * 100) %>%
  dplyr::ungroup()
mapeHRCV[11,] = c(as.character("Mean"), as.list(mean(mapeHRCV$mape)))
```










